// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcYpYrfGixfN0_fdlTkS6ZzaLgCt1Wpsk',
    appId: '1:544678282316:web:af8505aa623e69085a60e9',
    messagingSenderId: '544678282316',
    projectId: 'doctor-appointment-1d831',
    authDomain: 'doctor-appointment-1d831.firebaseapp.com',
    storageBucket: 'doctor-appointment-1d831.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebwT42sDnSfTw_i5dEtpy0AfFseneRhA',
    appId: '1:544678282316:android:c2ab97dc952f20e85a60e9',
    messagingSenderId: '544678282316',
    projectId: 'doctor-appointment-1d831',
    storageBucket: 'doctor-appointment-1d831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFfEdggbbX6IUYCrTCuzO6bci3D6KdOY',
    appId: '1:544678282316:ios:644b10c1fb21c1285a60e9',
    messagingSenderId: '544678282316',
    projectId: 'doctor-appointment-1d831',
    storageBucket: 'doctor-appointment-1d831.appspot.com',
    iosClientId: '544678282316-umu487svet9l1smr8798s79amt7irbt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFfEdggbbX6IUYCrTCuzO6bci3D6KdOY',
    appId: '1:544678282316:ios:432424be151b15555a60e9',
    messagingSenderId: '544678282316',
    projectId: 'doctor-appointment-1d831',
    storageBucket: 'doctor-appointment-1d831.appspot.com',
    iosClientId: '544678282316-bojv6cgk6ii3rgie19cm9aepjagi73vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment.RunnerTests',
  );
}
